// -*- C++ -*-
/**
 * Code generated by the The ACE ORB (TAO) IDL Compiler v4.0.1
 * TAO and the TAO IDL Compiler have been developed by:
 *       Center for Distributed Object Computing
 *       Washington University
 *       St. Louis, MO
 *       USA
 * and
 *       Distributed Object Computing Laboratory
 *       University of California at Irvine
 *       Irvine, CA
 *       USA
 * and
 *       Institute for Software Integrated Systems
 *       Vanderbilt University
 *       Nashville, TN
 *       USA
 *       https://www.isis.vanderbilt.edu/
 *
 * Information about TAO is available at:
 *     https://www.dre.vanderbilt.edu/~schmidt/TAO.html
 **/

// TAO_IDL - Generated from
// /opt/ACE_wrappers/TAO/TAO_IDL/be/be_codegen.cpp:1621

#include "CEtcdI.h"

// Implementation skeleton constructor
Search_i::Search_i ()
{
}

// Implementation skeleton destructor
Search_i::~Search_i ()
{
}

std::string Search_i::id ()
{
  // Add your implementation here
}

::CORBA::Boolean Search_i::put (
  const std::string key,
  const std::string value)
{
  // Add your implementation here
}

std::string Search_i::get (
  const std::string key)
{
  // Add your implementation here
}

void Search_i::del (
  const std::string key)
{
  // Add your implementation here
}

void Search_i::shutdown (
  const std::string password)
{
  // Add your implementation here
}

