// -*- C++ -*-
/**
 * Code generated by the The ACE ORB (TAO) IDL Compiler v4.0.1
 * TAO and the TAO IDL Compiler have been developed by:
 *       Center for Distributed Object Computing
 *       Washington University
 *       St. Louis, MO
 *       USA
 * and
 *       Distributed Object Computing Laboratory
 *       University of California at Irvine
 *       Irvine, CA
 *       USA
 * and
 *       Institute for Software Integrated Systems
 *       Vanderbilt University
 *       Nashville, TN
 *       USA
 *       https://www.isis.vanderbilt.edu/
 *
 * Information about TAO is available at:
 *     https://www.dre.vanderbilt.edu/~schmidt/TAO.html
 **/

// TAO_IDL - Generated from
// /opt/ACE_wrappers/TAO/TAO_IDL/be/be_codegen.cpp:1567

#ifndef CETCDI_VWIH8A_H_
#define CETCDI_VWIH8A_H_

#include "CEtcdS.h"

#if !defined (ACE_LACKS_PRAGMA_ONCE)
#pragma once
#endif /* ACE_LACKS_PRAGMA_ONCE */

class  Search_i
  : public virtual POA_Search
{
public:
  // Constructor
  Search_i ();

  // Destructor
  virtual ~Search_i ();

  virtual
  std::string id ();

  virtual
  ::CORBA::Boolean put (
    const std::string key,
    const std::string value);

  virtual
  std::string get (
    const std::string key);

  virtual
  void del (
    const std::string key);

  virtual
  void shutdown (
    const std::string password);
};


#endif /* CETCDI_H_  */
